### ISSUE TITLE
Segfault when using `List::from_pairs` in current master

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#346]
Simply using `List::from_pairs` seems to cause a segfault. Here's a simple example. I'm not sure if there's an easier way to create a reproducible example:

`Cargo.toml`
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr.git", rev = "1264ad5ae3c491247878470aceed584ba9a87844" }
```
`src/main.rs`:
```rust
use extendr_api::prelude::*;

fn main(){
    List::from_pairs([("foo", 4.into())]);
}
```
