### ISSUE TITLE
doctest fails on Windows with "LINK : fatal error LNK1181: cannot open input file 'R.lib'" when proc_macro = true

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#372]
(From https://github.com/extendr/extendr/pull/347#issuecomment-1030119516)

Here's the minimal reproducible example. Note that, if I change `proc_macro` to `false`, no error happens.

### `Cargo.toml`

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]

[dev-dependencies]
extendr-api = { path = "../extendr-api" }
```

### `src/lib.rs`

``` rs
/// ```
/// use extendr_api::prelude::*;
/// ```
fn foo() {}
```

### command

``` sh
cargo test --manifest-path foo/Cargo.toml --target=x86_64-pc-windows-gnu --doc -- --nocapture
```
