### ISSUE TITLE
R cmd check failure for ubuntu-latest (R-devel rust-stable)

### ISSUE THREAD

**Issue by donaldcampbelljr** [extendr/extendr#873]
Hello,

Our team is excited to implement this work for our own rust crates. We've recently encountered an issue with the R-CMD-Check github action. It seems that there is a failure for the `R-devel branch`, due to a warning "**Warning:   No rustc version reported prior to compilation".**

Example of failed action:
https://github.com/databio/gtars/actions/runs/12436597215/job/34724746884?pr=51

We have our github action, `R-CMD-check.yaml` set up like so:
```
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }} rust-${{ matrix.config.rust-version }})
    strategy:
      fail-fast: false
      matrix:
        config:
          #  - {os: windows-latest, r: 'release', rust-version: 'stable-msvc', rust-target: 'x86_64-pc-windows-gnu'}
          - {os: macOS-latest,   r: 'release', rust-version: 'stable'}
          - {os: ubuntu-latest,  r: 'release', rust-version: 'stable'}
          - {os: ubuntu-latest,  r: 'devel',   rust-version: 'stable'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.config.rust-version }}
          targets: ${{ matrix.config.rust-target }}
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck
          working-directory: ${{ github.workspace }}/bindings/r
      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ${{ github.workspace }}/bindings/r

```

Any suggestions for fixing this on our side, or is this a bug?

Thanks!
