### ISSUE TITLE
serialize extendr Strings

### ISSUE THREAD

**Issue by kbvernon** [extendr/extendr#876]
Serializing to `Strings` with `serde` doesn't seem to be supported atm:
```rust
use extendr_api::prelude::*;
use serde::{Deserialize, Serialize};

// this works
#[derive(Serialize)]
MyStruct {
  x: Vec<Rstr>
}

// this fails
#[derive(Serialize)]
MyStruct {
  x: Strings
}
```
Rust-analyzer says this:
```rust
the trait bound `extendr_api::Strings: Serialize` is not satisfied
for local types consider adding `#[derive(serde::Serialize)]` to your `extendr_api::Strings` type
for types from other crates check whether the crate offers a `serde` feature flag
```
And, for reference, this is in my TOML:
```toml
[dependencies]
extendr-api = { version = "*", features = ["serde"] }
```
