### ISSUE TITLE
Compilation issue for linux machines

### ISSUE THREAD

**Issue by DyfanJones** [extendr/extendr#902]
Hi everyone! 👋

I hope you're all doing well. I'm reaching out because I've encountered some compilation issues with the heck package that have been reported by CRAN. I'm hoping to get some help to resolve these issues.

### Description
There have been some compilation issues reported by CRAN for the heck package. You can view the detailed check results [here](https://cran.r-project.org/web/checks/check_results_heck.html).

I was able to reproduce the issue using R-hub GitHub Actions. You can see the logs and details of the run [here](https://github.com/DyfanJones/heck/actions/runs/14037249181/job/39298206844).

I believe this issue might be related to [extendr/extendr#890](https://github.com/extendr/extendr/issues/890).

### Details
I am not very familiar with the compilation code, so I am having difficulty resolving this issue. Below is the current Cargo.toml configuration for the heck package:

```toml
[package]
name = "heck"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "heck"

[dependencies]
extendr-api = "0.7.1"
heck = "0.5.0"
```
